[package]
name = "kernel_core"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { version = "^0.13", default-features = false }
byteorder = { version = "^1.5", default-features = false }
