//! Definitions for user space remote procedure call (RPC) protocol.
use bitfield::bitfield;
use bytemuck::{Contiguous, Pod, Zeroable};
use kernel_api::Message;

/// The type of an RPC message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Contiguous)]
#[repr(u8)]
pub enum MessageType {
    /// A request to run a procedure.
    Request,
    /// A request to run a procedure and then send the response elsewhere.
    ProxiedRequest,
    /// A response indicating the result of a [`Request`].
    Response,
    /// A notification that does not require a response.
    Notification,
}

impl From<u8> for MessageType {
    fn from(value: u8) -> Self {
        Self::from_integer(value).expect("message type is known")
    }
}

bitfield! {
    /// The header for an RPC message.
    pub struct MessageHeader(u64);
    impl Debug;
    /// The type of this message.
    pub u8, into MessageType, msg_type, set_type: 4, 0;
    /// Message op-code. This is interpreted by the receiver, and should determine the exact procedure/method invoked for Requests/Notifications and the result code (ok/error) for Responses.
    pub u32, op_code, set_op_code: 32, 28;
    /// This value is generated by senders of Requests, and copied to the relevant Response that is sent back.
    /// This field is unspecified for Notifications and should be available for applications.
    pub u32, correlation_id, set_correlation_id: 64, 32;
}

impl Clone for MessageHeader {
    fn clone(&self) -> Self {
        *self
    }
}

impl Copy for MessageHeader {}
unsafe impl Zeroable for MessageHeader {}
unsafe impl Pod for MessageHeader {}

/// An RPC service.
pub trait Service {
    /// Handle an incoming request or notification message.
    /// The service must free the message and any attached buffers when it is finished with them.
    fn handle_message(&self, msg: Message) -> impl Future<Output = ()> + Send + 'static;
}
