[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
kernel_core = { path = "../kernel_core"}
itertools = { version = "^0.13", default-features = false }
byteorder = { version = "^1.5", default-features = false }
bitfield = { version = "^0.17" }
spin = "^0.9"

